export const actionTypes = {
  PENDING: 'PENDING',
  FULFILLED: 'FULFILLED',
  REJECTED: 'REJECTED',
  RESET: 'RESET',
  INITIAL_SERVICES: 'INITIAL_SERVICES',
  UPDATED: 'UPDATED',
  REMOVED: 'REMOVED',
  PATCHED: 'PATCHED',
  CREATED: 'CREATED',
};

export const serviceMethods = {
  FIND: 'FIND',
  GET: 'GET',
  UPDATE: 'UPDATE',
  REMOVE: 'REMOVE',
  PATCH: 'PATCH',
  CREATE: 'CREATE',
};

export const serviceEvents = {
  UPDATED: 'UPDATED',
  REMOVED: 'REMOVED',
  PATCHED: 'PATCHED',
  CREATED: 'CREATED',
};
